"""add field volumes_count in table Books

Revision ID: 420d53212137
Revises: 9fdf74fa7a70
Create Date: 2026-03-11 01:42:41.953043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "420d53212137"
down_revision: Union[str, Sequence[str], None] = "9fdf74fa7a70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column("volumes_count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "volumes_count")
    # ### end Alembic commands ###
