"""add field short_description

Revision ID: 8ec0657fe86d
Revises: 437ba5f0c6aa
Create Date: 2026-03-10 01:38:52.474243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ec0657fe86d"
down_revision: Union[str, Sequence[str], None] = "437ba5f0c6aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column("short_description", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "short_description")
    # ### end Alembic commands ###
