"""add field author_id in table Books and relationship

Revision ID: 9fdf74fa7a70
Revises: 8ec0657fe86d
Create Date: 2026-03-10 22:24:42.026412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9fdf74fa7a70"
down_revision: Union[str, Sequence[str], None] = "8ec0657fe86d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("author_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_books_author_id"), "books", ["author_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_books_author_id_authors"),
        "books",
        "authors",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_books_author_id_authors"), "books", type_="foreignkey")
    op.drop_index(op.f("ix_books_author_id"), table_name="books")
    op.drop_column("books", "author_id")
    # ### end Alembic commands ###
