"""add table Author

Revision ID: 437ba5f0c6aa
Revises: b3788c69a5a2
Create Date: 2026-03-05 22:57:25.071990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "437ba5f0c6aa"
down_revision: Union[str, Sequence[str], None] = "b3788c69a5a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("patronymic_name", sa.String(length=256), nullable=True),
        sa.Column("last_name", sa.String(length=256), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint(
            "first_name",
            "patronymic_name",
            "last_name",
            name="uq_author_full_name",
        ),
    )
    op.create_index(op.f("ix_authors_first_name"), "authors", ["first_name"], unique=False)
    op.create_index(op.f("ix_authors_is_deleted"), "authors", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_authors_last_name"), "authors", ["last_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_authors_last_name"), table_name="authors")
    op.drop_index(op.f("ix_authors_is_deleted"), table_name="authors")
    op.drop_index(op.f("ix_authors_first_name"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
